./compile
./sender 11 1 "ABC"
./sender 14 12 "ABCDEFGHI"
./sender 13 12345 "ABCDEFGHI"
#./sender 14 12345 "ABCDEFGHIFGSELGJSLGJESLGJSEGILSEJGSLKKLSDGJSRDGSERFGGSEGSEGSEGSEGSEGSEGSEGSEGSEGIIRJGSRLGJLSRGJLRISGJLSRGJRLSIGJILSRGILRSGJIRGJLSRGJSRILJGEGIESJILESJGILSEJGILSEJGILESJFGILESJF:EFJISEFJ:ESFJSEIFJLESJFELSJFILEJFILSEJFILSEJFRGJISRGJISRLGJSIERGJILSRJGILRSJGLRSJLISRGJILRJSGILSRJGLGRSILGJLRISGJLRISGJSRILGJIL"
./sender 12 12345 "ABCDEFGHI"
